# test if the package has alfreadty been published on the pyPI target url

name: _check_exists
on:
  workflow_call:
    inputs:
      url:
        type: string
        required: true
    outputs:
      exists:
        description: "Whether the distribution has already been published"
        value: ${{ jobs.check_exists.outputs.exists }}

jobs:
  check_exists:
    runs-on: ubuntu-latest
    container: python:3.13-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Prepare Python
        run: |
          pip install -q uv
          uv venv --seed $VENV
          . $VENV/bin/activate
          uv pip install toml
      - name: Install curl/jq
        run: |
          apt-get update
          apt-get install -y curl jq
      - name: Check if version already exists
        id: check_exists
        run: |
          . $VENV/bin/activate
          PACKAGE_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          PACKAGE_NAME=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['name'])")
          echo "Checking: $PACKAGE_NAME==$PACKAGE_VERSION"
          if curl -s "${{ inputs.url }}" | jq -r '.releases | keys[]' | grep -q "^$PACKAGE_VERSION$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
