# Print diagnostics contents

name: _diag
on:
  workflow_call: {}

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson( github ) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson( job ) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson( steps ) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson( runner ) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson( strategy ) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson( matrix ) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Print event info
        run: |
          echo "   EVENT: $GITHUB_EVENT_NAME"
          echo "     REF: $GITHUB_REF"
          echo "REF_TYPE: $GITHUB_REF_TYPE"
          echo "REF_NAME: $GITHUB_REF_NAME"
      - name: Show event payload keys
        run: |
          jq -r '["keys:", (. | keys[]) ] | .[]' "$GITHUB_EVENT_PATH" || true
      - name: List tags pointing at this commit
        run: |
          git init -q
          git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          git fetch -q --tags origin "${GITHUB_SHA}"
          git checkout -q -B tmp "${GITHUB_SHA}"
          echo "Tags pointing at HEAD:"
          git tag --points-at HEAD || true
